### ISSUE TITLE
'requirements.txt' pins number of libs that are either stale or not on PyPi

### ISSUE THREAD

**Issue by ganmohim** [PracticalDL/Practical-Deep-Learning-Book#53]
Before I open an issue, I have to admit that this is a great piece of work that cuts to the chase.
I got the book today. And, I already finished first chapter. It is the best intro I ever read on AI books. ~~Koul~~ Cool  trick with Dr. May Carson :wink:.

**Issue:**
Unless I missed something, the readers will have minor hiccup in installing the [requirements.txt](https://github.com/PracticalDL/Practical-Deep-Learning-Book/blob/master/requirements.txt). I spent about half an hour, and I found some of the pinned packages are either not on PyPi or versions are stale. Please try steps below to reproduce:

1) System running Ubuntu 16.04 LTS
2) Python version 3.7.4
3) Created venv > then activate it
4) Then issued this command: `pip install -r requirements.txt`

**Outcome:**
Some packages will be either unable to install or can not be found in PyPi server (e.g.  apturl).
There are few, but I mentioned one as example. It seems the requirement file may need some maintenance

Thanks.

**Comment by meherkasam** [comment]
Thank you for your kind words. We're glad you're enjoying the book.

And thank you for bringing the issue of the `requirements.txt` to our attention. We'd built our virtual environment a while ago back when we had started writing the book and it appears that some of those packages may have gone out of date. I've updated the repo to remove `requirements.txt` altogether, since we have instructions for installing necessary packages in each chapter's `README.md` already.

https://github.com/PracticalDL/Practical-Deep-Learning-Book/pull/55
